### ISSUE TITLE
[Bug] Naming resources in serverless.yml results in a failed deploy

### ISSUE THREAD

**Issue by shindakun** [shindakun/cautious-waffle#56]
https://github.com/shindakun/cautious-waffle/pull/43 added a character's table to the serverless.yml. The first deploy worked as expected but subsequent @renovate-bot PR's failed due to a table already existing. Turns out this is a known issue and has been for some time, https://github.com/serverless/serverless/issues/3183. It doesn't look like the Serverless devs will be adding "skip if exists" anytime soon. That's kind of a shame, seems like such an obvious feature.  🤷‍♂️

```
resources:
  Resources:
    charactersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy : Retain
      Properties:
        TableName: characters
        AttributeDefinitions:
          - AttributeName: guid
            AttributeType: S
        KeySchema:
          - AttributeName: guid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
```

```
  Serverless Error ---------------------------------------
 
  An error occurred: charactersTable - characters already exists in stack arn:aws:cloudformation:us-west-2:782450989625:stack/cautious-waffle-renovate-pin-dependencies/b6e66cc0-6b33-11ea-89f6-0231aca8377c.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.13.0
     Framework Version:         1.67.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
 
Build step failed: serverless deploy
failure
Deploy failed!
Error: Build step failed: serverless deploy
```
